//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictBookGenre
    {
        public DictBookGenre()
        {
            this.Book = new HashSet<Book>();
        }
    
        public int BookGenreId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Book> Book { get; set; }
    }
}
